CREATE DATABASE IF NOT EXISTS `ajax_db` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `ajax_db`;

CREATE TABLE `user_info`(
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `username` VARCHAR(255) DEFAULT NOT NULL,
    `password` VARCHAR(255) DEFAULT NOT NULL,
    `email` VARCHAR(255) DEFAULT NOT NULL,
    `registration_date` DATETIME DEFAULT NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;